import "server-only";

import { createServiceSupabase } from "@/lib/supabase/server";

/**
 * Customer ID lookups.
 *
 * The actual `SB-XXXXX` id is generated by the database trigger
 * `set_customer_id_on_insert` (see PR-02). Application code does NOT
 * pick or override the id — it just reads back what the trigger
 * assigned after the row is inserted, so the `profile.customer_id`
 * column can be shown to the user.
 */

/**
 * Returns the `customer_id` for the profile with `profileId`, or `null`
 * if no such profile exists.
 */
export async function getCustomerIdForProfile(
  profileId: string,
): Promise<string | null> {
  const supabase = createServiceSupabase();
  const { data, error } = await supabase
    .from("profiles")
    .select("customer_id")
    .eq("id", profileId)
    .maybeSingle();
  if (error) {
    throw new Error(`[auth/customerId] lookup failed: ${error.message}`);
  }
  const row = data as { customer_id: string | null } | null;
  return row?.customer_id ?? null;
}
