import { NextResponse, type NextRequest } from "next/server";
import { ZodError } from "zod";

import { errJson } from "@/lib/api/responses";
import { UnauthorizedError, requireUser } from "@/lib/auth/session";
import { completeProfileBodySchema } from "@/lib/auth/validation";
import { createServiceSupabase } from "@/lib/supabase/server";
import authContent from "@/content/contentConstants.json";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

/**
 * POST /api/auth/register/complete-profile
 *
 * Step 4 of the registration wizard. Requires an authenticated user
 * (the password-setup step already signed them in). On success the
 * profile is flipped to `profile_verified` and the autogenerated
 * `customer_id` is returned so the dashboard can render it on first
 * load.
 */
export async function POST(request: NextRequest): Promise<NextResponse> {
  let ctx;
  try {
    ctx = await requireUser();
  } catch (e) {
    if (e instanceof UnauthorizedError) {
      return errJson(
        "unauthenticated",
        authContent.auth.errors.unauthenticated,
        401,
      );
    }
    throw e;
  }

  if (ctx.profile.status === "profile_verified") {
    return errJson(
      "already_complete",
      "Profile is already complete.",
      409,
    );
  }

  let raw: unknown;
  try {
    raw = await request.json();
  } catch {
    return errJson("invalid_body", "Body must be valid JSON", 400);
  }

  let body;
  try {
    body = completeProfileBodySchema.parse(raw);
  } catch (e) {
    if (e instanceof ZodError) {
      return errJson(
        "invalid_body",
        e.issues[0]?.message ?? "Invalid request body",
        400,
      );
    }
    throw e;
  }

  const admin = createServiceSupabase();

  // Ensure no *other* verified profile already owns this mobile number.
  // A row with a `pending:<uuid>` placeholder mobile is fine — that's
  // the current user's own row before completion.
  const { data: mobileClashRow, error: mobileLookupError } = await admin
    .from("profiles")
    .select("id, status")
    .eq("mobile", body.mobile)
    .maybeSingle();
  if (mobileLookupError) {
    console.error(
      "[api/register/complete-profile] mobile lookup failed",
      mobileLookupError,
    );
    return errJson("internal_error", "Internal server error", 500);
  }
  if (mobileClashRow) {
    const row = mobileClashRow as { id: string; status: string };
    if (row.id !== ctx.user.id && row.status === "profile_verified") {
      return errJson("mobile_taken", authContent.auth.errors.mobileTaken, 409);
    }
  }

  const { data: updated, error: updateError } = await admin
    .from("profiles")
    .update({
      full_name: body.full_name,
      mobile: body.mobile,
      address: body.address,
      status: "profile_verified",
    })
    .eq("id", ctx.user.id)
    .select("customer_id")
    .single();
  if (updateError || !updated) {
    console.error(
      "[api/register/complete-profile] profile update failed",
      updateError,
    );
    return errJson("internal_error", "Could not save your profile.", 500);
  }

  return NextResponse.json({
    ok: true,
    customer_id: (updated as { customer_id: string }).customer_id,
    redirect: "/dash",
  });
}
